In [57]:
import pandas as pd


import matplotlib.pyplot as plt
from sklearn.decomposition import NMF 
from sklearn.preprocessing import Normalizer ,MaxAbsScaler
from sklearn.pipeline import make_pipeline

In [2]:
df = pd.read_csv('../data/final_per_90_and_pAdj.csv')

In [5]:
# ## dont need club for NMF 

clubs = df['Club']
df.drop(columns=['Club'],inplace=True)

In [6]:
# ## dont need club for NMF 

clubs = df['Club']
df.drop(columns=['Club'],inplace=True)
missing = [df.isnull().sum(),100*df.isnull().mean()]
m = pd.DataFrame(missing)
m = m.T
m.columns=['count', '%']
m = m.sort_values(by='count',ascending=False)
m.head()

count          %
Base Salary           184.0  26.099291
True_tackle_pct        33.0   4.680851
fb_id                   0.0   0.000000
PKatt                   0.0   0.000000
pAdj_Tackles_Mid_3rd    0.0   0.000000

In [8]:
df['Base Salary'] = df['Base Salary'].str.replace('$','')
df['Base Salary'] = df['Base Salary'].str.replace(',','')
df['Base Salary'] = pd.to_numeric(df['Base Salary'])
df[['Base Salary']].info()
cols = ['Base Salary']
for col in cols:
    print(df[col].mean())
    df[col] = df[col].fillna(df[col].mean())

missing = [df.isnull().sum(),100*df.isnull().mean()]
m = pd.DataFrame(missing)
m = m.T
m.columns=['count', '%']
m = m.sort_values(by='count',ascending=False)
m.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 705 entries, 0 to 704
Data columns (total 1 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Base Salary  521 non-null    float64
dtypes: float64(1)
memory usage: 5.6 KB
381064.81381957774


<ipython-input-8-3be890ae56c0>:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will*not* be treated as literal strings when regex=True.
  df['Base Salary'] = df['Base Salary'].str.replace('$','')


count         %
True_tackle_pct        33.0  4.680851
fb_id                   0.0  0.000000
PKatt                   0.0  0.000000
pAdj_Tackles_Mid_3rd    0.0  0.000000
pAdj_Tackles_Def_3rd    0.0  0.000000

In [9]:
df['True_tackle_pct'].describe()

count    672.000000
mean      23.926205
std       12.244691
min        0.000000
25%       18.378937
50%       25.091964
75%       30.775008
max      101.660156
Name: True_tackle_pct, dtype: float64

In [10]:
mini_df = df[['player_name','Position', 'Nineties', 'xA', 'Key_pass',
       'Comp_prog', 'Total_Cmp', 'Total_Att', 'Total_Cmp_pct',
       'Total_Tot_Dist', 'Total_Prg_Dist',
              'Short_Cmp', 'Short_Att',
       'Short_Cmp_pct', 'Medium_Cmp', 'Medium_Att', 'Medium_Cmp_pct',
       'Long_Cmp', 'Long_Att', 'Long_Cmp_pct', 'touches', 'touches_def_box',
       'touches_def_3rd', 'touches_mid_3rd', 'touches_att_3rd',
       'touches_att_box', 'touch_live', 'dribble_Succ', 'dribble_Att',
       'dribble_Succ_pct',
              'num_dribble_past', 'dribble_megs', 'carries',
       'carries_dist', 'carries_prog_dist', 'carries_prog', 'carries_att_3rd',
       'carries_att_box', 'miss_control', 'dispossed', 'recep_targ',
       'recep_succ', 'recept_pct', 'Fouls_drawn', 'Offsides', 'Crosses',
       'PK_won', 'Aerial_win_pct', 
              'Gls', 'Sh', 'SoT', 'SoT%', 'Sh/90',
       'SoT/90', 'G/Sh', 'G/SoT', 'Dist', 'FK',
              'PK', 'PKatt', 'xG', 'npxG',
       'npxG/Sh', 
              
              # cant use negatives
              # 'G-xG',
              # 'np:G-xG',
              
             
             ]]

mini_df.shape

(705, 63)

In [11]:
test = df[[
    
    # 'Nineties', 'xA', 'Key_pass',
    #    'Comp_prog', 'Total_Cmp', 'Total_Att', 'Total_Cmp_pct',
    #    'Total_Tot_Dist', 'Total_Prg_Dist',
    #           'Short_Cmp', 'Short_Att',
    #    'Short_Cmp_pct', 'Medium_Cmp', 'Medium_Att', 'Medium_Cmp_pct',
    #    'Long_Cmp', 'Long_Att', 'Long_Cmp_pct', 'touches', 'touches_def_box',
    #    'touches_def_3rd', 'touches_mid_3rd', 'touches_att_3rd',
    #    'touches_att_box', 'touch_live', 'dribble_Succ', 'dribble_Att',
    #    'dribble_Succ_pct',
    #           'num_dribble_past', 'dribble_megs', 'carries',
    #    'carries_dist', 'carries_prog_dist', 'carries_prog', 'carries_att_3rd',
    #    'carries_att_box', 'miss_control', 'dispossed', 'recep_targ',
    #    'recep_succ', 'recept_pct', 'Fouls_drawn', 'Offsides', 'Crosses',
    #    'PK_won', 'Aerial_win_pct', 
        
           'PK_won', 'Aerial_win_pct', 
              'Gls',  'SoT', 'SoT%', 'Sh/90',
       'SoT/90', 'G/Sh', 'G/SoT', 'Dist', 'FK',
              'PK', 'PKatt', 'xG', 'npxG',
       'npxG/Sh']]

In [12]:
>>> from sklearn.preprocessing import MaxAbsScaler
>>> X = [[ 1., -1.,  2.],
...      [ 2.,  0.,  0.],
...      [ 0.,  1., -1.]]
>>> transformer = MaxAbsScaler().fit(X)
>>> transformer
MaxAbsScaler()
>>> transformer.transform(X)
# array([[ 0.5, -1. ,  1. ],
#        [ 1. ,  0. ,  0. ],
#        [ 0. ,  1. , -0.5]])

array([[ 0.5, -1. ,  1. ],
       [ 1. ,  0. ,  0. ],
       [ 0. ,  1. , -0.5]])

In [14]:
>>> from sklearn.preprocessing import Normalizer
>>> X = [[4, 1, 2, 2],
...      [1, 3, 9, 3],
...      [5, 7, 5, 1]]
>>> transformer = Normalizer().fit(X)  # fit does nothing.
>>> transformer
Normalizer()
>>> transformer.transform(X)
# array([[0.8, 0.2, 0.4, 0.4],
#        [0.1, 0.3, 0.9, 0.3],
#        [0.5, 0.7, 0.5, 0.1]])

array([[0.8, 0.2, 0.4, 0.4],
       [0.1, 0.3, 0.9, 0.3],
       [0.5, 0.7, 0.5, 0.1]])

In [16]:

X = mini_df  # reading the score data
c = 6
X_float = X.select_dtypes(float)
# Create a MaxAbsScaler: scaler
transformer = MaxAbsScaler().fit(test)


scaled_X= transformer.transform(test)
transformer = Normalizer().fit(scaled_X)
normed_X= transformer.transform(scaled_X)
# Create an NMF model: nmf
 
    
nmf = NMF(n_components=4 ,max_iter=1000,init='nndsvda', random_state=0)


W = nmf.fit_transform(normed_X)
H = nmf.components_
err = nmf.reconstruction_err_
print(err)

6.378261580683327


In [17]:
H.shape

(4, 16)

In [18]:
W.shape

(705, 4)

In [19]:
err

6.378261580683327

In [20]:
# Create a DataFrame: components_df
components_df = pd.DataFrame(nmf.components_,columns=test.columns)

# Print the shape of the DataFrame
print(components_df.shape)

# Select row 3: component
component = components_df.iloc[3]

# Print result of nlargest
print(component.nlargest())

(4, 16)
Dist       2.177742
Sh/90      0.730105
npxG/Sh    0.591483
npxG       0.402876
xG         0.386791
Name: 3, dtype: float64


In [22]:
components_df

PK_won  Aerial_win_pct       Gls       SoT      SoT%     Sh/90    SoT/90  \
0  0.000000        6.017662  0.000000  0.000000  0.018549  0.000000  0.000000   
1  0.000000        0.000000  0.005532  0.576528  4.132607  0.000000  0.083692   
2  0.663884        0.050507  2.203446  1.062644  0.000000  0.105344  0.091378   
3  0.000000        0.000000  0.000000  0.169471  0.000000  0.730105  0.196494   

       G/Sh     G/SoT      Dist        FK        PK     PKatt        xG  \
0  0.000000  0.046089  0.082573  0.005230  0.000000  0.000000  0.015402   
1  0.076753  0.036676  0.099595  0.069893  0.000000  0.000000  0.103183   
2  0.152224  0.229151  0.000000  0.574311  0.301455  0.354876  1.765977   
3  0.035606  0.042650  2.177742  0.000000  0.000000  0.000000  0.386791   

       npxG   npxG/Sh  
0  0.012179  0.000000  
1  0.139459  0.052599  
2  1.630711  0.139552  
3  0.402876  0.591483

In [21]:
for i in range(len(components_df)):
    component = components_df.iloc[i]
    print(component.nlargest())

Aerial_win_pct    6.017662
Dist              0.082573
G/SoT             0.046089
SoT%              0.018549
xG                0.015402
Name: 0, dtype: float64
SoT%    4.132607
SoT     0.576528
npxG    0.139459
xG      0.103183
Dist    0.099595
Name: 1, dtype: float64
Gls       2.203446
xG        1.765977
npxG      1.630711
SoT       1.062644
PK_won    0.663884
Name: 2, dtype: float64
Dist       2.177742
Sh/90      0.730105
npxG/Sh    0.591483
npxG       0.402876
xG         0.386791
Name: 3, dtype: float64


In [135]:
components_df

PK_won  Aerial_win_pct       Gls       SoT      SoT%     Sh/90    SoT/90  \
0  0.00000        0.000000  0.000000  0.102266  1.455660  0.000000  0.007368   
1  0.00000        0.000000  0.000000  0.059656  0.000000  0.312015  0.087929   
2  0.00000        1.711045  0.000000  0.000000  0.008206  0.000000  0.000000   
3  0.47562        0.078150  1.608191  0.976330  0.050898  0.099581  0.112710   

       G/Sh     G/SoT      Dist        FK        PK     PKatt        xG  \
0  0.050424  0.003588  0.033342  0.000873  0.000000  0.000000  0.000000   
1  0.023510  0.078036  0.984500  0.000000  0.000000  0.000000  0.146910   
2  0.000000  0.044578  0.067796  0.003869  0.000000  0.000000  0.001465   
3  0.067544  0.116809  0.000000  0.462872  0.214276  0.253318  1.388685   

       npxG   npxG/Sh  
0  0.000000  0.046112  
1  0.155241  0.271433  
2  0.004542  0.000000  
3  1.306416  0.069530

In [136]:
err

6.452761548384023

# I have this normed before putting into nmf not after , lowers error but could be obscuring data

In [66]:

errors = {}
components_dict = {}
for c in range(1,10):
    X = mini_df  # reading the score data
    
    c = c
    # Create a MaxAbsScaler: scaler
    transformer = MaxAbsScaler().fit(test)


    scaled_X= transformer.transform(test)
    # Create an NMF model: nmf
    # normed_X= transformer.transform(scaled_X)
    nmf = NMF(n_components=c,max_iter=100000,init='nndsvda', random_state=0)
    print(nmf)


    W = nmf.fit_transform(scaled_X)
    H = nmf.components_
    err = nmf.reconstruction_err_
    errors[c]=err
    # Create a DataFrame: components_df
    components_df = pd.DataFrame(nmf.components_,columns=test.columns)
    # put data frame in dictionary to observe 
    components_dict[c]=components_df

    


NMF(init='nndsvda', max_iter=100000, n_components=1, random_state=0)
NMF(init='nndsvda', max_iter=100000, n_components=2, random_state=0)
NMF(init='nndsvda', max_iter=100000, n_components=3, random_state=0)
NMF(init='nndsvda', max_iter=100000, n_components=4, random_state=0)
NMF(init='nndsvda', max_iter=100000, n_components=5, random_state=0)
NMF(init='nndsvda', max_iter=100000, n_components=6, random_state=0)
NMF(init='nndsvda', max_iter=100000, n_components=7, random_state=0)
NMF(init='nndsvda', max_iter=100000, n_components=8, random_state=0)
NMF(init='nndsvda', max_iter=100000, n_components=9, random_state=0)


# wow the itterations over the nmf different components definity looks pretty good , could try to tune alpha later but for now looks decent, going to try all features to see what happens , then try just key features

In [67]:
for i in components_dict:
    print('This is nmf with :',i, ' components')
    print(' error = ',errors[i])
    for a in range(len(components_dict[i])):
        component = components_dict[i].iloc[a]
        print(component.nlargest())
    print('\n')

This is nmf with : 1  components
 error =  11.519325617981426
Aerial_win_pct    3.041323
SoT%              1.913908
Gls               0.910899
xG                0.767191
npxG              0.724720
Name: 0, dtype: float64


This is nmf with : 2  components
 error =  8.556441661131474
Aerial_win_pct    4.124167
SoT%              0.878657
Dist              0.315655
G/SoT             0.017421
npxG/Sh           0.014986
Name: 0, dtype: float64
SoT%    1.791255
Gls     1.417969
xG      1.138869
npxG    1.065786
SoT     1.005248
Name: 1, dtype: float64


This is nmf with : 3  components
 error =  7.3957419177184125
Aerial_win_pct    4.572424
SoT%              0.126216
Dist              0.085527
G/SoT             0.038048
xG                0.034930
Name: 0, dtype: float64
Gls     1.787491
xG      1.265746
npxG    1.131989
SoT     0.848700
SoT%    0.640912
Name: 1, dtype: float64
SoT%       2.623333
Dist       0.755502
SoT        0.514048
npxG/Sh    0.294693
npxG       0.257047
Name: 2, dtype: 

In [68]:
H.shape

(9, 16)

In [69]:
errors

{1: 11.519325617981426,
 2: 8.556441661131474,
 3: 7.3957419177184125,
 4: 6.263223432321639,
 5: 5.4193089166868855,
 6: 4.650486601993271,
 7: 3.876739707192627,
 8: 3.1141884624225757,
 9: 2.347202184697552}

In [76]:
## on mini not test 


errors = {}
components_dict = {}
for c in range(1,10):
    X = mini_df  # reading the score data
    
    c = c
    # Create a MaxAbsScaler: scaler
    transformer = MaxAbsScaler().fit(X.select_dtypes(float))


    scaled_X= transformer.transform(X)
    # Create an NMF model: nmf
    # normed_X= transformer.transform(scaled_X)
    nmf = NMF(n_components=c,max_iter=100000,init='nndsvda', random_state=0)
    print(nmf)


    W = nmf.fit_transform(scaled_X)
    H = nmf.components_
    err = nmf.reconstruction_err_
    errors[c]=err
    # Create a DataFrame: components_df
    components_df = pd.DataFrame(nmf.components_,columns=test.columns)
    # put data frame in dictionary to observe 
    components_dict[c]=components_df

    


ValueError: could not convert string to float: 'Carles Gil'

In [70]:
# components_df = pd.DataFrame(nmf.components_,columns=mini_df.columns)

# print(component_df.shape)
        
# Create a DataFrame: components_df
components_df = pd.DataFrame(nmf.components_,columns=test.columns)

# Print the shape of the DataFrame
print(components_df.shape)

# Select row 3: component
component = components_df.iloc[3]

# Print result of nlargest
print(component.nlargest())

(9, 16)
Dist       2.831614
Sh/90      0.754028
npxG/Sh    0.160631
SoT        0.117501
G/SoT      0.005091
Name: 3, dtype: float64


In [71]:
# transformer = Normalizer().fit(W)
# normed_X= transformer.transform(W)
normed_df = pd.DataFrame(W,index=df.player_name.values)
normed_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 705 entries, Carles Gil to Kamron Habibullah
Data columns (total 9 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   0       705 non-null    float64
 1   1       705 non-null    float64
 2   2       705 non-null    float64
 3   3       705 non-null    float64
 4   4       705 non-null    float64
 5   5       705 non-null    float64
 6   6       705 non-null    float64
 7   7       705 non-null    float64
 8   8       705 non-null    float64
dtypes: float64(9)
memory usage: 55.1+ KB


In [72]:
## looks all wrong with normed first - need to adjust 

In [73]:
jm = normed_df.loc['Jonathan Mensah']
sims = normed_df.dot(jm)

sims.nlargest(10)

Dante Sealy            0.024404
Yordy Reyna            0.024339
Daniel Musovski        0.023490
Daryl Dike             0.021739
Sergio Santos Gomes    0.021702
Javier Hernández       0.021446
Jáder Obrian           0.020998
Jordan Perruzza        0.020847
Cristian Arango        0.020446
Robert Castellanos     0.020362
dtype: float64

In [63]:
wz = normed_df.loc['Walker Zimmerman']
sims = normed_df.dot(wz)

sims.nlargest(10)

Abu Danladi          0.035413
Dante Sealy          0.027083
Jordan Perruzza      0.023360
Tony Rocha           0.021676
Jarosław Niezgoda    0.020125
Adam Buksa           0.018459
Miguel Berry         0.017891
Anderson Julio       0.017783
Javier Hernández     0.016787
Christian Ramirez    0.016572
dtype: float64

In [27]:
mini_df.shape

(705, 63)

In [56]:
df_n = df.drop(columns= ['G-xG','np:G-xG'])
df_n.shape

(705, 103)

In [55]:
df.columns.values

array(['fb_id', 'player_name', 'Squad_from_op', 'Opposing_Poss',
       'Opposing_Touches', 'Player', 'Nation', 'Position',
       'Tackle_pct_won', 'Nineties', 'xA', 'Key_pass', 'Comp_prog',
       'Total_Cmp', 'Total_Att', 'Total_Cmp_pct', 'Total_Tot_Dist',
       'Total_Prg_Dist', 'Short_Cmp', 'Short_Att', 'Short_Cmp_pct',
       'Medium_Cmp', 'Medium_Att', 'Medium_Cmp_pct', 'Long_Cmp',
       'Long_Att', 'Long_Cmp_pct', 'touches', 'touches_def_box',
       'touches_def_3rd', 'touches_mid_3rd', 'touches_att_3rd',
       'touches_att_box', 'touch_live', 'dribble_Succ', 'dribble_Att',
       'dribble_Succ_pct', 'num_dribble_past', 'dribble_megs', 'carries',
       'carries_dist', 'carries_prog_dist', 'carries_prog',
       'carries_att_3rd', 'carries_att_box', 'miss_control', 'dispossed',
       'recep_targ', 'recep_succ', 'recept_pct', 'Fouls_drawn',
       'Offsides', 'Crosses', 'PK_won', 'Aerial_win_pct', 'Gls', 'Sh',
       'SoT', 'SoT%', 'Sh/90', 'SoT/90', 'G/Sh', 'G/SoT', 'Dist'