In [2]:
import pandas as pd


import matplotlib.pyplot as plt
from sklearn.decomposition import NMF 
from sklearn.preprocessing import Normalizer ,MaxAbsScaler
from sklearn.pipeline import make_pipeline

In [3]:
df = pd.read_csv('../data/final_per_90_and_pAdj.csv')

In [4]:
# ## dont need club for NMF 

df.drop(columns=['Unnamed: 0_y', 'First Name', 'Last Name', 'name', '_merge','Club','Guaranteed Compensation'],inplace=True)

In [6]:
cols = ['G/Sh','G/SoT','SoT%','npxG/Sh','Dist','Base Salary']
for col in cols:
    print(df[col].mean())
    df[col] = df[col].fillna(df[col].mean())

missing = [df.isnull().sum(),100*df.isnull().mean()]
m = pd.DataFrame(missing)
m = m.T
m.columns=['count', '%']
m = m.sort_values(by='count',ascending=False)
m.head()

0.009939746728555306
0.027277585423982696
30.38505942275043
0.013745106122472362
2.395677172663176
381115.9694656489


count    %
fb_id              0.0  0.0
carries_att_3rd    0.0  0.0
G/Sh               0.0  0.0
SoT/90             0.0  0.0
Sh/90              0.0  0.0

In [7]:
mini_df = df[['player_name','Position', 'Nineties', 'xA', 'Key_pass',
       'Comp_prog', 'Total_Cmp', 'Total_Att', 'Total_Cmp_pct',
       'Total_Tot_Dist', 'Total_Prg_Dist',
              'Short_Cmp', 'Short_Att',
       'Short_Cmp_pct', 'Medium_Cmp', 'Medium_Att', 'Medium_Cmp_pct',
       'Long_Cmp', 'Long_Att', 'Long_Cmp_pct', 'touches', 'touches_def_box',
       'touches_def_3rd', 'touches_mid_3rd', 'touches_att_3rd',
       'touches_att_box', 'touch_live', 'dribble_Succ', 'dribble_Att',
       'dribble_Succ_pct',
              'num_dribble_past', 'dribble_megs', 'carries',
       'carries_dist', 'carries_prog_dist', 'carries_prog', 'carries_att_3rd',
       'carries_att_box', 'miss_control', 'dispossed', 'recep_targ',
       'recep_succ', 'recept_pct', 'Fouls_drawn', 'Offsides', 'Crosses',
       'PK_won', 'Aerial_win_pct', 
              'Gls', 'Sh', 'SoT', 'SoT%', 'Sh/90',
       'SoT/90', 'G/Sh', 'G/SoT', 'Dist', 'FK',
              'PK', 'PKatt', 'xG', 'npxG',
       'npxG/Sh', 
              
              # cant use negatives
              # 'G-xG',
              # 'np:G-xG',
              
             
             ]]

mini_df.shape

(705, 74)

In [76]:
test = df[[
    
    # 'Nineties', 'xA', 'Key_pass',
    #    'Comp_prog', 'Total_Cmp', 'Total_Att', 'Total_Cmp_pct',
    #    'Total_Tot_Dist', 'Total_Prg_Dist',
    #           'Short_Cmp', 'Short_Att',
    #    'Short_Cmp_pct', 'Medium_Cmp', 'Medium_Att', 'Medium_Cmp_pct',
    #    'Long_Cmp', 'Long_Att', 'Long_Cmp_pct', 'touches', 'touches_def_box',
    #    'touches_def_3rd', 'touches_mid_3rd', 'touches_att_3rd',
    #    'touches_att_box', 'touch_live', 'dribble_Succ', 'dribble_Att',
    #    'dribble_Succ_pct',
    #           'num_dribble_past', 'dribble_megs', 'carries',
    #    'carries_dist', 'carries_prog_dist', 'carries_prog', 'carries_att_3rd',
    #    'carries_att_box', 'miss_control', 'dispossed', 'recep_targ',
    #    'recep_succ', 'recept_pct', 'Fouls_drawn', 'Offsides', 'Crosses',
    #    'PK_won', 'Aerial_win_pct', 
        
           'PK_won', 'Aerial_win_pct', 
              'Gls',  'SoT', 'SoT%', 'Sh/90',
       'SoT/90', 'G/Sh', 'G/SoT', 'Dist', 'FK',
              'PK', 'PKatt', 'xG', 'npxG',
       'npxG/Sh']]

In [49]:
>>> from sklearn.preprocessing import MaxAbsScaler
>>> X = [[ 1., -1.,  2.],
...      [ 2.,  0.,  0.],
...      [ 0.,  1., -1.]]
>>> transformer = MaxAbsScaler().fit(X)
>>> transformer
MaxAbsScaler()
>>> transformer.transform(X)
# array([[ 0.5, -1. ,  1. ],
#        [ 1. ,  0. ,  0. ],
#        [ 0. ,  1. , -0.5]])

array([[ 0.5, -1. ,  1. ],
       [ 1. ,  0. ,  0. ],
       [ 0. ,  1. , -0.5]])

In [ ]:
>>> from sklearn.preprocessing import Normalizer
>>> X = [[4, 1, 2, 2],
...      [1, 3, 9, 3],
...      [5, 7, 5, 1]]
>>> transformer = Normalizer().fit(X)  # fit does nothing.
>>> transformer
Normalizer()
>>> transformer.transform(X)
array([[0.8, 0.2, 0.4, 0.4],
       [0.1, 0.3, 0.9, 0.3],
       [0.5, 0.7, 0.5, 0.1]])

In [153]:

X = mini_df  # reading the score data
c = 6
X_float = X.select_dtypes(float)
# Create a MaxAbsScaler: scaler
transformer = MaxAbsScaler().fit(test)


scaled_X= transformer.transform(test)
transformer = Normalizer().fit(scaled_X)
normed_X= transformer.transform(scaled_X)
# Create an NMF model: nmf
 
    
nmf = NMF(n_components=4 ,max_iter=1000,init='nndsvda', random_state=0)


W = nmf.fit_transform(normed_X)
H = nmf.components_
err = model.reconstruction_err_
print(err)

6.288812097362449


In [154]:
H.shape

(4, 16)

In [155]:
W.shape

(705, 4)

In [156]:
err

6.288812097362449

In [157]:
# Create a DataFrame: components_df
components_df = pd.DataFrame(nmf.components_,columns=test.columns)

# Print the shape of the DataFrame
print(components_df.shape)

# Select row 3: component
component = components_df.iloc[3]

# Print result of nlargest
print(component.nlargest())

(4, 16)
Dist       2.228989
Sh/90      0.708892
npxG/Sh    0.613582
npxG       0.353268
xG         0.334608
Name: 3, dtype: float64


In [161]:
for i in range(len(components_df)):
    component = components_df.iloc[i]
    print(component.nlargest())

Aerial_win_pct    6.081475
Dist              0.221036
G/SoT             0.157426
npxG              0.016341
FK                0.013705
Name: 0, dtype: float64
Gls       2.032533
xG        1.754855
npxG      1.650883
SoT       1.261480
PK_won    0.601026
Name: 1, dtype: float64
SoT%       3.794964
SoT        0.264608
G/Sh       0.131340
npxG/Sh    0.124355
Dist       0.117369
Name: 2, dtype: float64
Dist       2.228989
Sh/90      0.708892
npxG/Sh    0.613582
npxG       0.353268
xG         0.334608
Name: 3, dtype: float64


In [135]:
components_df

PK_won  Aerial_win_pct       Gls       SoT      SoT%     Sh/90    SoT/90  \
0  0.00000        0.000000  0.000000  0.102266  1.455660  0.000000  0.007368   
1  0.00000        0.000000  0.000000  0.059656  0.000000  0.312015  0.087929   
2  0.00000        1.711045  0.000000  0.000000  0.008206  0.000000  0.000000   
3  0.47562        0.078150  1.608191  0.976330  0.050898  0.099581  0.112710   

       G/Sh     G/SoT      Dist        FK        PK     PKatt        xG  \
0  0.050424  0.003588  0.033342  0.000873  0.000000  0.000000  0.000000   
1  0.023510  0.078036  0.984500  0.000000  0.000000  0.000000  0.146910   
2  0.000000  0.044578  0.067796  0.003869  0.000000  0.000000  0.001465   
3  0.067544  0.116809  0.000000  0.462872  0.214276  0.253318  1.388685   

       npxG   npxG/Sh  
0  0.000000  0.046112  
1  0.155241  0.271433  
2  0.004542  0.000000  
3  1.306416  0.069530

In [136]:
err

6.452761548384023

In [137]:
H

array([[0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.02266427e-01,
        1.45566011e+00, 0.00000000e+00, 7.36785867e-03, 5.04242562e-02,
        3.58815291e-03, 3.33416634e-02, 8.72678844e-04, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 4.61123925e-02],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 5.96563546e-02,
        0.00000000e+00, 3.12014574e-01, 8.79286350e-02, 2.35099933e-02,
        7.80359491e-02, 9.84499562e-01, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 1.46910263e-01, 1.55241299e-01, 2.71433181e-01],
       [0.00000000e+00, 1.71104543e+00, 0.00000000e+00, 0.00000000e+00,
        8.20601497e-03, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        4.45784649e-02, 6.77959291e-02, 3.86899204e-03, 0.00000000e+00,
        0.00000000e+00, 1.46507110e-03, 4.54226925e-03, 0.00000000e+00],
       [4.75619547e-01, 7.81499248e-02, 1.60819123e+00, 9.76329578e-01,
        5.08982986e-02, 9.95814009e-02, 1.12710302e-01, 6.754

In [145]:

errors = {}
for c in range(1,10):
    X = mini_df  # reading the score data
    
    c = c
    # Create a MaxAbsScaler: scaler
    transformer = MaxAbsScaler().fit(test)


    scaled_X= transformer.transform(test)
    # Create an NMF model: nmf
    normed_X= transformer.transform(scaled_X)
    nmf = NMF(n_components=c,max_iter=100000,init='nndsvda', random_state=0)
    print(nmf)


    W = nmf.fit_transform(normed_X)
    H = nmf.components_
    err = model.reconstruction_err_
    errors[c]=err

    


NMF(init='nndsvda', max_iter=100000, n_components=1, random_state=0)
NMF(init='nndsvda', max_iter=100000, n_components=2, random_state=0)
NMF(init='nndsvda', max_iter=100000, n_components=3, random_state=0)
NMF(init='nndsvda', max_iter=100000, n_components=4, random_state=0)
NMF(init='nndsvda', max_iter=100000, n_components=5, random_state=0)
NMF(init='nndsvda', max_iter=100000, n_components=6, random_state=0)
NMF(init='nndsvda', max_iter=100000, n_components=7, random_state=0)
NMF(init='nndsvda', max_iter=100000, n_components=8, random_state=0)
NMF(init='nndsvda', max_iter=100000, n_components=9, random_state=0)


/Users/robertrustia/opt/anaconda3/lib/python3.8/site-packages/sklearn/decomposition/_nmf.py:1090: ConvergenceWarning: Maximum number of iterations 100000 reached. Increase it to improve convergence.
  warnings.warn("Maximum number of iterations %d reached. Increase it to"


In [146]:
errors

{1: 6.288812097362449,
 2: 6.288812097362449,
 3: 6.288812097362449,
 4: 6.288812097362449,
 5: 6.288812097362449,
 6: 6.288812097362449,
 7: 6.288812097362449,
 8: 6.288812097362449,
 9: 6.288812097362449}